---
- name: "Deploying Website From Github"
  hosts: amazon
  become: true
  vars:
    repo_url: "https://github.com/vyshnavlal/test.git"
    packages:
      - git
      - docker
      - python2-pip
    repo: "vyshnavlal/gitflaskapp"
    docker_user: <docker user>
    docker_password: <docker password>

  tasks:
    
    - name: "Package Instalaltion"
      yum:
        name: "{{ packages }}"
        state: present

    - name: "Adding ec2-user to docker group"
      user:
        name: ec2-user
        group: docker
        append: yes

    - name: "Install docker client for python"
      pip:
        name: docker-py
        state: present

    - name: "Restarting docker"
      service:
        name: docker
        state: restarted
        enabled: true
            
    - name: "Clonning Repo {{ repo_url }} "
      git:
        repo: "{{ repo_url }}"
        dest: /var/gitsite/
      register: git_status
        
        
    - debug:
        var: git_status

    - name: "Log into Docker Hub"
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
    
    - name: "Removing old latest image"
      when: git_status.changed
      docker_image:
        name: "{{ repo }}:latest"
        state: absent

    - name: "Build the Docker image"
      when: git_status.changed
      docker_image:
        build:
          path: /var/gitsite/
        name: "{{ repo }}"
        tag: "{{ item }}"
        source: build
        push: yes
      with_items:
        - "{{ git_status.after }}"
        - latest
    - name: "creating docker conatiner using the image created"
      when: git_status.changed
      docker_container:
        name: gitflaskapp
        image: "{{ repo }}"
        state: started
        recreate: yes
